version: '3.8'

services:
  # FastAPI Application
  app:
    build: .
    container_name: kelz_complete_app
    ports:
      - "3002:3002"
    volumes:
      - ./app:/app/app
      - ./temp:/app/temp
    environment:
      PYTHONPATH: /app
      PYTHONUNBUFFERED: 1
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      GOOGLE_APPLICATION_CREDENTIALS: /app/qsync-genesys-bb7e26814113.json
      PROJECT_ID: qsync-genesys
      LOCATION: eu
      PROCESSOR_ID: 1a3f804e6db79958
      PROCESSOR_VERSION: rc
    networks:
      - kelz_network
    restart: unless-stopped



networks:
  kelz_network:
    driver: bridge
